# Generated by Django 4.2.4 on 2023-09-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date_uopdated',
            new_name='date_updated',
        ),
    ]
